var products=[
{name:"RCV Ultimate CV Axle Set",brand:"RCV",cat:"Transmisión",sku:"CVJ3525-BSP-RCV",price:1599.95,stock:"En stock",fit:"Y61 GU 1997+ · H233B · 31 spline",img:"https://cdn11.bigcommerce.com/s-ix0ixasu7w/images/stencil/500x500/products/2559/1992/cvj3525-bsp-rcv__66445.1760379738.jpg?c=1",icon:"⚙️"},
{name:"Trail-Gear Birfield Kit",brand:"TRAIL-GEAR",cat:"Transmisión",sku:"TGI-300809-KIT",price:0,stock:"Consultar",fit:"Y61 / GU 1997–2013 · todos los motores",img:"",icon:"⚙️"},
{name:"Longfield Front Axle — Short",brand:"TRAIL-GEAR",cat:"Transmisión",sku:"TGI-300974-KIT",price:196.71,stock:"Disponible",fit:"Y61 1997–2013 · 30/31 spline",img:"",icon:"🔩"},
{name:"Longfield Front Axle — Long",brand:"TRAIL-GEAR",cat:"Transmisión",sku:"TGI-300975-KIT",price:196.71,stock:"Disponible",fit:"Y61 1997–2013 · 30/31 spline",img:"",icon:"🔩"},
{name:"King 2.0 Steering Stabilizer",brand:"KING",cat:"Dirección",sku:"Y61-KING-2.0",price:290,stock:"Disponible",fit:"Nissan Patrol Y61 1997+",img:"",icon:"↔️"},
{name:"ICON Centerline Steering Stabilizer",brand:"ICON",cat:"Dirección",sku:"82020",price:317.19,stock:"Stock limitado",fit:"Nissan Patrol Y61 1997+",img:"",icon:"↔️"},
{name:"ARB Air Locker H260 37 Spline",brand:"ARB",cat:"Transmisión",sku:"RD215",price:1399.95,stock:"Disponible",fit:"Y61 1997–2016 · H260 · 37 spline",img:"",icon:"⚙️"},
{name:"Dobinsons IMS Front Shock 3 in",brand:"DOBINSONS",cat:"Suspensión",sku:"IMS51-60116",price:1400,stock:"Disponible",fit:"Y60/Y61 1987–2015 · individual",img:"",icon:"🛞"},
{name:"FOX Performance Front Shock",brand:"FOX",cat:"Suspensión",sku:"985-24-076",price:229.95,stock:"Low stock",fit:"Y60/Y61 · delantero · lift 3–5.5 in",img:"https://serenity-foxfactory.asset.akeneo.cloud/fox_asset_family/media/985_24_226_fox_truck_performance_smooth_body_shock_pr_1600x1600.png",icon:""},
{name:"FOX Reservoir Rear Shock 3–5.5 in",brand:"FOX",cat:"Suspensión",sku:"985-26-142",price:0,stock:"Consultar",fit:"Y60/Y61 1988–2023 · lift 3–5.5 in",img:"",icon:"🛞"},
{name:"aFe Momentum GT Pro 5R Intake",brand:"aFe POWER",cat:"Motor",sku:"54-76107",price:451,stock:"Disponible",fit:"Y61 2017–2018 · TB48 4.8L",img:"",icon:"🌬️"},
{name:"ARB Gearbox Packer Kit",brand:"ARB",cat:"Transmisión",sku:"GQGK02",price:98,stock:"Disponible",fit:"Nissan Patrol Y61 SWB",img:"",icon:"🔧"},
{name:"Extended Brake Line Kit",brand:"TRAIL-GEAR",cat:"Frenos",sku:"304503-KIT",price:0,stock:"Consultar",fit:"Y61 Non-ABS · lift 2–5.9 in",img:"https://www.sneveysoffroad.com/image/cache/catalog/Trail-Gear/304177-KIT-FLCL-500x500.jpg",icon:"🛞"}];
var cats=[["Inicio","⌂",""],["Suspensión","","/assets/suspension.svg"],["Frenos","","/assets/brakes.svg"],["Dirección","","/assets/steering.svg"],["Transmisión","","/assets/transmission.svg"],["Motor","","/assets/motor.svg"],["Refrigeración","","/assets/cooling.svg"],["Eléctrico","","/assets/electrical.svg"]],C=[],active="Inicio";
try{C=JSON.parse(localStorage.getItem("patrolY61Cart")||"[]")||[]}catch(e){}
function money(v){return v?("US$ "+v.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})):"Consultar"}
function save(){try{localStorage.setItem("patrolY61Cart",JSON.stringify(C))}catch(e){}var n=0,t=0;C.forEach(function(x){n+=x.q;t+=products[x.i].price*x.q});count.textContent=n;cartTotal.textContent="US$ "+t.toLocaleString("en-US",{maximumFractionDigits:0})}
function renderNav(){nav.innerHTML="";cats.forEach(function(c){nav.innerHTML+='<button class="'+(active===c[0]?"active":"")+'" data-cat="'+c[0]+'">'+c[1]+'<br>'+c[0]+'</button>'});nav.querySelectorAll("[data-cat]").forEach(function(b){b.onclick=function(){filterCat(this.dataset.cat)}})}
function renderCats(){categories.innerHTML="";cats.slice(1).forEach(function(c){categories.innerHTML+='<button class="cat" data-cat="'+c[0]+'"><img class="catPhoto" src="'+c[2]+'" alt="'+c[0]+'"><small>'+c[0]+'</small></button>'});categories.querySelectorAll("[data-cat]").forEach(function(b){b.onclick=function(){filterCat(this.dataset.cat)}})}
function filterCat(c){active=c;search.value="";renderNav();render();document.getElementById("products").scrollIntoView({behavior:"smooth"})}
function render(){var q=search.value.toLowerCase(),shown=0;grid.innerHTML="";products.forEach(function(p,i){if(active!=="Inicio"&&p.cat!==active)return;if((p.name+" "+p.brand+" "+p.cat+" "+p.sku+" "+p.fit).toLowerCase().indexOf(q)<0)return;shown++;var pic=p.img?'<img src="'+p.img+'" alt="'+p.name+'" onerror="this.parentNode.innerHTML=\'<div class=&quot;fallback&quot;>'+p.icon+'<small>Imagen del producto en actualización</small></div>\'">':'<div class="fallback"><div style="font-size:18px;font-weight:950;letter-spacing:.08em">PATROL Y61 PARTS</div><small>FOTO REAL PENDIENTE DE VERIFICACIÓN</small></div>';grid.innerHTML+='<article class="card"><div class="photo">'+pic+'</div><div class="body"><span class="brand">'+p.brand+'</span><h3>'+p.name+'</h3><div class="sku">'+p.sku+'</div><div class="fit">'+p.fit+'</div><div class="price">'+money(p.price)+'</div><div class="stock">● '+p.stock+'</div><div class="actions"><button class="details" data-d="'+i+'">DETALLES</button><button class="add" data-a="'+i+'">🛒 AGREGAR</button></div></div></article>'});resultCount.textContent=shown+" productos";bind()}
function bind(){document.querySelectorAll("[data-a]").forEach(function(b){b.onclick=function(){add(+this.dataset.a)}});document.querySelectorAll("[data-d]").forEach(function(b){b.onclick=function(){details(+this.dataset.d)}})}
function add(i){var x=C.find(function(z){return z.i===i});x?x.q++:C.push({i:i,q:1});save();cartTop.animate([{transform:"scale(1)"},{transform:"scale(1.08)"},{transform:"scale(1)"}],{duration:250})}
function details(i){var p=products[i];panel.innerHTML='<h2>'+p.name+'</h2><span class="brand">'+p.brand+'</span><div class="line"><span>SKU</span><b>'+p.sku+'</b></div><div class="line"><span>Compatibilidad</span><b>'+p.fit+'</b></div><div class="line"><span>Disponibilidad</span><b>'+p.stock+'</b></div><div class="line"><span>Precio</span><b>'+money(p.price)+'</b></div><button class="pay" id="detailAdd">AGREGAR AL CARRITO</button><p class="notice">Antes del despacho confirmamos año, motor y configuración de tu Y61.</p>';overlay.style.display="block";detailAdd.onclick=function(){add(i);openCart()}}
function openCart(){var h="<h2>Tu carrito</h2>",t=0;if(!C.length)h+='<p class="notice">Tu carrito está vacío.</p>';C.forEach(function(x,k){var p=products[x.i];t+=p.price*x.q;h+='<div class="line"><div><b>'+p.name+'</b><br><small>'+p.sku+'</small></div><div><div class="qty"><button data-m="'+k+'">−</button><b>'+x.q+'</b><button data-p="'+k+'">+</button></div><b>'+money(p.price*x.q)+'</b></div></div>'});h+='<div class="line"><b>Subtotal</b><b>'+money(t)+'</b></div><button class="pay" id="checkout">CONTINUAR PEDIDO</button><p class="notice">El proveedor de origen permanece privado. Patrol Y61 Parts gestiona el abastecimiento y la orden.</p>';panel.innerHTML=h;overlay.style.display="block";panel.querySelectorAll("[data-m]").forEach(function(b){b.onclick=function(){var k=+this.dataset.m;C[k].q--;if(C[k].q<1)C.splice(k,1);save();openCart()}});panel.querySelectorAll("[data-p]").forEach(function(b){b.onclick=function(){C[+this.dataset.p].q++;save();openCart()}});checkout.onclick=function(){panel.innerHTML='<h2>Pedido Patrol Y61 Parts</h2><p>Tu carrito está listo. El cobro online se habilitará al conectar la cuenta merchant.</p><button class="pay" onclick="overlay.style.display=\'none\'">VOLVER A LA TIENDA</button>'}}
search.oninput=function(){active="Inicio";renderNav();render()};cartTop.onclick=openCart;cartBottom.onclick=openCart;close.onclick=function(){overlay.style.display="none"};overlay.onclick=function(e){if(e.target===overlay)overlay.style.display="none"};viewAll.onclick=function(){filterCat("Inicio")};home.onclick=function(){scrollTo(0,0)};find.onclick=function(){search.focus()};mobileCats.onclick=function(){categories.scrollIntoView({behavior:"smooth"})};renderNav();renderCats();save();render();